export enum BysonTypes {
  String = "string",
  Number = "number",
  Boolean = "bool",
  Object = "object",
  Array = "array",
  Date = "date",
  Null = "null",
  Any = "any",
  Mixed = "mixed",
  Undefined = "undefined",
  ObjectId = "objectId",
  Timestamp = "timestamp",
  // Float = "decimal",
}
