name: tests

on:
  pull_request:
    paths:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies and run tests
        run: |
          npm install
          npm run test:ci
